backend:
  name: git-gateway
  branch: decap

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: posts
    label: Posts
    folder: src/contents/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD",
          time_format: false,
        }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
